dubbo:
  scan:
    base-packages: jenny.learn.springboot.dubbo.provider.service.impl
  application:
    name: learn-springboot-dubbo-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 28080

server:
  port: 8091
