server:
  port: 8094
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jenny?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ENC(gVom118l917bhblhvMu+ow==)
    password: ENC(6Vx42Si5xhl0AMLZrqFayt26qyKTOAlw)
    # 没有下面一行，初始化脚本可能不会执行
    initialization-mode: always
    data: classpath:data.sql
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  config-location: classpath:mybatis-config.xml