server:
  port: 8992
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jasmine?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ENC(gVom118l917bhblhvMu+ow==)
    password: ENC(KgYyrjHmaXPa5W7knxXc7Q==)
    # 没有下面一行，初始化脚本可能不会执行
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:data.sql
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  config-location: classpath:mybatis-config.xml
app:
  workerId: 1
  datacenterId: 1
